config/routes.rb
Rails.application.routes.draw do
  get '/artists', to: 'artist#index', as: 'artists'
  get '/artists/:id', to: 'artist#show', as: 'artist'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  name        :string
#  image_url   :string
#  released_at :string
#  artist_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  name        :string
#  number      :integer
#  preview_url :string
#  song_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Song < ApplicationRecord
  belongs_to :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artist/index.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="row">
      <% @artists.each do |artist|  %>
        <div class="col-sm-5 col-md-3">
          <div class="thumbnail">
            <img src="<%= artist.image_url %>" alt="" />
            <div class="caption">
              <h3><%= artist.name %></h3>
              <p><%= link_to 'Ver Mas', artist_path(id: artist.id), class: "btn btn-primary" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artist/show.html.erb
<div class="container">
  <div class="col-md-8">
    <div class="row">
      <% @albums.each do |album|  %>
        <div class="col-sm-5 col-md-3">
          <div class="thumbnail">
            <img src="<%= album.image_url %>" alt="" />
            <div class="caption">
              <h3><%= album.name %></h3>
              <h4><%= album.released_at %></h4>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <img src="<%= @artist.image_url %>" alt="" />
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-default navbar-inverse">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Real Music</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="#">Artistas <span class="sr-only">(current)</span></a></li>
                  <li><a href="#">Mi musica</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi Cuenta<span class="caret"></span></a>
                   <ul class="dropdown-menu">
                     <li><a href="#">Make it Real</a></li>
                   </ul>
                 </li>
               </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
        </div>
      </div>
    <%= yield %>
  </body>
</html>